name: GravestonePlugin
version: '${project.version}'
main: io.github.maliciousfiles.gravestone.GravestonePlugin
api-version: '1.21'
authors: [MaliciousFiles]
description: Stores items on player death
